<?xml version="1.0" encoding="utf-8"?><Database Name="OnlineRates" Class="OnlineRatesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GOMZAS;Initial Catalog=OnlineRates;Integrated Security=True;User ID=sa;Password=123456;" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OnlineRatesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bank" Member="Banks">
    <Type Name="Bank">
      <Column Name="BankId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BankName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Bank_RatesinBank" Member="RatesinBanks" ThisKey="BankId" OtherKey="IdBank" Type="RatesinBank" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RatesinBank" Member="RatesinBanks">
    <Type Name="RatesinBank">
      <Column Name="RateBankId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdBank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="USD_Buying" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="USD_Selling" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EUR_Buying" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="EUR_Selling" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RUB_Buying" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RUB_Selling" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DateofRate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Bank_RatesinBank" Member="Bank" ThisKey="IdBank" OtherKey="BankId" Type="Bank" IsForeignKey="true" />
    </Type>
  </Table>
</Database>