
USE [master]
GO

/****** Object:  Database [OnlineRates]    Script Date: 3/2/2016 5:55:49 PM ******/
CREATE DATABASE [OnlineRates]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnlineRates', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\OnlineRates.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OnlineRates_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\OnlineRates_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OnlineRates] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnlineRates].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OnlineRates] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [OnlineRates] SET ANSI_NULLS OFF
GO

ALTER DATABASE [OnlineRates] SET ANSI_PADDING OFF
GO

ALTER DATABASE [OnlineRates] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [OnlineRates] SET ARITHABORT OFF
GO

ALTER DATABASE [OnlineRates] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [OnlineRates] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [OnlineRates] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [OnlineRates] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [OnlineRates] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [OnlineRates] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [OnlineRates] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [OnlineRates] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [OnlineRates] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [OnlineRates] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [OnlineRates] SET  DISABLE_BROKER
GO

ALTER DATABASE [OnlineRates] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [OnlineRates] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [OnlineRates] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [OnlineRates] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [OnlineRates] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [OnlineRates] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [OnlineRates] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [OnlineRates] SET RECOVERY FULL
GO

ALTER DATABASE [OnlineRates] SET  MULTI_USER
GO

ALTER DATABASE [OnlineRates] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [OnlineRates] SET DB_CHAINING OFF
GO

ALTER DATABASE [OnlineRates] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [OnlineRates] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

EXEC sys.sp_db_vardecimal_storage_format N'OnlineRates', N'ON'
GO

USE [OnlineRates]
GO

/****** Object:  Table [dbo].[Bank]    Script Date: 3/2/2016 5:55:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Customer]    Script Date: 3/2/2016 5:55:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[RatesinBank]    Script Date: 3/2/2016 5:55:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [OnlineRates] SET  READ_WRITE
GO
